const L=['hu','en','es'];
let lang=localStorage.getItem('mesterweb_lang')||'hu';
const T={
 hu:{back:'← Főoldal',contact:'Kapcsolat',sources:'Képforrások',topbar_text:'MODERN WEBOLDALAK KISVÁLLALKOZÁSOKNAK',topbar_link:'30 napos próba →',nav_services:'Szolgáltatások',nav_examples:'Példák',nav_why:'Miért MesterWeb?',nav_process:'Hogyan működik?',nav_about:'Rólam',nav_faq:'GYIK',nav_contact:'Kapcsolat',nav_cta:'30 napos próba',footer_desc:'Modern weboldalak kisvállalkozásoknak.',footer_menu:'Menü',footer_choice:'Landing vagy weboldal?',footer_trial:'30 napos próba',footer_sources:'Képforrások',credit_note:'Képforrások és fotósok megtekintése →',footer_copy:'© 2026 MesterWeb – Weboldalak vállalkozásoknak',footer_demo:'Bemutató weboldal – a tartalom és az elérhetőségek később személyre szabhatók.'},
 en:{back:'← Home',contact:'Contact',sources:'Image sources',topbar_text:'MODERN WEBSITES FOR SMALL BUSINESSES',topbar_link:'30-day trial →',nav_services:'Services',nav_examples:'Examples',nav_why:'Why MesterWeb?',nav_process:'How it works',nav_about:'About me',nav_faq:'FAQ',nav_contact:'Contact',nav_cta:'30-day trial',footer_desc:'Modern websites for small businesses.',footer_menu:'Menu',footer_choice:'Landing page or website?',footer_trial:'30-day trial',footer_sources:'Image sources',credit_note:'View image sources and photographers →',footer_copy:'© 2026 MesterWeb – Websites for businesses',footer_demo:'Demo website – content and contact details can be personalised later.'},
 es:{back:'← Inicio',contact:'Contacto',sources:'Fuentes de imágenes',topbar_text:'PÁGINAS WEB MODERNAS PARA PEQUEÑOS NEGOCIOS',topbar_link:'Prueba de 30 días →',nav_services:'Servicios',nav_examples:'Ejemplos',nav_why:'¿Por qué MesterWeb?',nav_process:'Cómo funciona',nav_about:'Sobre mí',nav_faq:'FAQ',nav_contact:'Contacto',nav_cta:'Prueba 30 días',footer_desc:'Páginas web modernas para pequeños negocios.',footer_menu:'Menú',footer_choice:'¿Landing page o web completa?',footer_trial:'Prueba de 30 días',footer_sources:'Fuentes de imágenes',credit_note:'Ver fuentes de imágenes y fotógrafos →',footer_copy:'© 2026 MesterWeb – Páginas web para negocios',footer_demo:'Web de demostración – el contenido y los datos de contacto se pueden personalizar.'}
};
function setLang(x){if(!L.includes(x))x='hu';lang=x;document.documentElement.lang=x;document.querySelectorAll('[data-content-lang]').forEach(e=>e.hidden=e.dataset.contentLang!==x);document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===x));const tx=T[x];document.querySelectorAll('[data-i18n]').forEach(e=>{if(tx[e.dataset.i18n])e.textContent=tx[e.dataset.i18n]});localStorage.setItem('mesterweb_lang',x)}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));setLang(lang)});
