const L=['hu','en','es'];
let lang=localStorage.getItem('mesterweb_lang')||'es';
const T={
 hu:{meta_title:'Weboldal próba 30 napig – MesterWeb',meta_description:'Próbálja ki személyre szabott weboldalát 30 napig, saját domain és tárhely nélkül. MesterWeb.',nav_trial:'30 napos próba',footer_trial:'30 napos próba',back:'← Főoldal',contact:'Kapcsolat',sources:'Képforrások',topbar_text:'MODERN WEBOLDALAK KISVÁLLALKOZÁSOKNAK',topbar_link:'Ingyenes konzultáció →',nav_services:'Szolgáltatások',nav_examples:'Példák',nav_crm:'Digitális rendszerek',nav_why:'Miért MesterWeb?',nav_process:'Hogyan működik?',nav_about:'Rólam',nav_faq:'GYIK',nav_contact:'Kapcsolat',nav_cta:'Érdeklődöm',footer_desc:'Modern weboldalak kisvállalkozásoknak.',footer_menu:'Menü',footer_choice:'Landing vagy weboldal?',footer_whatsapp:'WhatsApp – csak üzenet',footer_sources:'Képforrások',credit_note:'Képforrások és fotósok megtekintése →',footer_copy:'© 2026 MesterWeb – Weboldalak vállalkozásoknak',footer_demo:'Bemutató weboldal – a tartalom és az elérhetőségek később személyre szabhatók.'},
 en:{meta_title:'30-Day Website Trial – MesterWeb',meta_description:'Try your personalised website for 30 days before deciding whether to keep it. MesterWeb.',nav_trial:'30-day website trial',footer_trial:'30-day website trial',back:'← Home',contact:'Contact',sources:'Image sources',topbar_text:'MODERN WEBSITES FOR SMALL BUSINESSES',topbar_link:'Free consultation →',nav_services:'Services',nav_examples:'Examples',nav_crm:'Digital systems',nav_why:'Why MesterWeb?',nav_process:'How it works',nav_about:'About me',nav_faq:'FAQ',nav_contact:'Contact',nav_cta:'Enquire now',footer_desc:'Modern websites for small businesses.',footer_menu:'Menu',footer_choice:'Landing page or website?',footer_whatsapp:'WhatsApp – messages only',footer_sources:'Image sources',credit_note:'View image sources and photographers →',footer_copy:'© 2026 MesterWeb – Websites for businesses',footer_demo:'Demo website – content and contact details can be personalised later.'},
 es:{meta_title:'Prueba de web durante 30 días – MesterWeb',meta_description:'Pruebe su web personalizada durante 30 días antes de decidir si quiere conservarla. MesterWeb.',nav_trial:'Prueba de web durante 30 días',footer_trial:'Prueba de web durante 30 días',back:'← Inicio',contact:'Contacto',sources:'Fuentes de imágenes',topbar_text:'PÁGINAS WEB MODERNAS PARA PEQUEÑOS NEGOCIOS',topbar_link:'Consulta gratuita →',nav_services:'Servicios',nav_examples:'Ejemplos',nav_crm:'Sistemas digitales',nav_why:'¿Por qué MesterWeb?',nav_process:'Cómo funciona',nav_about:'Sobre mí',nav_faq:'FAQ',nav_contact:'Contacto',nav_cta:'Solicitar información',footer_desc:'Páginas web modernas para pequeños negocios.',footer_menu:'Menú',footer_choice:'¿Landing page o web completa?',footer_whatsapp:'WhatsApp – solo mensajes',footer_sources:'Fuentes de imágenes',credit_note:'Ver fuentes de imágenes y fotógrafos →',footer_copy:'© 2026 MesterWeb – Páginas web para negocios',footer_demo:'Web de demostración – el contenido y los datos de contacto se pueden personalizar.'}
};
function setLang(x){if(!L.includes(x))x='es';lang=x;document.documentElement.lang=x;document.querySelectorAll('[data-content-lang]').forEach(e=>e.hidden=e.dataset.contentLang!==x);document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===x));const tx=T[x];document.querySelectorAll('[data-i18n]').forEach(e=>{if(tx[e.dataset.i18n])e.textContent=tx[e.dataset.i18n]});document.querySelectorAll('[data-i18n-content]').forEach(e=>{if(tx[e.dataset.i18nContent])e.setAttribute('content',tx[e.dataset.i18nContent])});if(tx.meta_title)document.title=tx.meta_title;localStorage.setItem('mesterweb_lang',x)}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));setLang(lang)});
