const clients=[['José Martínez','Torrevieja','+34 600 123 456','Baño completo','Activo'],['Ana López','Guardamar','+34 611 234 567','Cocina','Activo'],['Carlos Ruiz','Alicante','+34 622 345 678','Terraza','Seguimiento'],['María Sánchez','Santa Pola','+34 633 456 789','Pintura interior','Nuevo'],['David Moreno','Orihuela','+34 644 567 890','Reforma integral','Activo']];
const works=[['Casa Martínez','Torrevieja','Baño completo',72,'En curso'],['Piso López','Guardamar','Cocina',38,'En curso'],['Terraza Ruiz','Alicante','Terraza',90,'Casi terminado'],['Villa Moreno','Orihuela','Reforma integral',18,'Planificación']];
const quotes=[['P-2026-018','José Martínez','Baño completo','2.450 €','Aceptado'],['P-2026-019','Ana López','Cocina','4.980 €','Pendiente'],['P-2026-020','María Sánchez','Pintura','1.180 €','Enviado'],['P-2026-021','David Moreno','Reforma integral','18.750 €','Borrador']];
const docs=[['Presupuesto_P-2026-018.pdf','José Martínez','Presupuesto','18/09/2026'],['Contrato_Martinez.pdf','José Martínez','Contrato','19/09/2026'],['Factura_anticipo_Lopez.pdf','Ana López','Factura','20/09/2026'],['Plano_cocina.pdf','Ana López','Plano','20/09/2026']];
const $=s=>document.querySelector(s), content=$('#content'), title=$('#title');
function pill(s){let c=s.includes('Acept')||s.includes('Activo')||s.includes('terminado')?'green':s.includes('Pend')||s.includes('curso')?'orange':'';return `<span class="pill ${c}">${s}</span>`}
function dashboard(){title.textContent='Resumen';content.innerHTML=`<div class="cards"><div class="card"><div class="muted">CLIENTES ACTIVOS</div><div class="metric">12</div><div class="delta">+3 este mes</div></div><div class="card"><div class="muted">OBRAS EN CURSO</div><div class="metric">5</div><div class="delta">2 próximas a finalizar</div></div><div class="card"><div class="muted">PRESUPUESTOS ABIERTOS</div><div class="metric">3</div><div class="delta">8.610 € pendientes</div></div><div class="card"><div class="muted">PRÓXIMAS TAREAS</div><div class="metric">6</div><div class="delta">2 para hoy</div></div></div><div class="grid2"><div class="panel"><h2>Obras en curso</h2>${works.slice(0,3).map(w=>`<div class="row"><div class="grow"><div class="strong">${w[0]}</div><div class="muted">${w[1]} · ${w[2]}</div><div class="bar"><i style="width:${w[3]}%"></i></div></div><b>${w[3]}%</b></div>`).join('')}</div><div class="panel"><h2>Próximas tareas</h2><div class="row"><div class="grow"><b>09:30 · Llamar a José</b><div class="muted">Confirmar azulejos</div></div></div><div class="row"><div class="grow"><b>12:00 · Visita de obra</b><div class="muted">Guardamar</div></div></div><div class="row"><div class="grow"><b>17:00 · Enviar presupuesto</b><div class="muted">María Sánchez</div></div></div></div></div>`}
function tableView(name,heads,rows){title.textContent=name;content.innerHTML=`<div class="toolbar"><input class="filter" placeholder="Buscar en ${name.toLowerCase()}…"><button class="primary" onclick="demoAdd('${name}')">+ Nuevo</button></div><div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr class="click" onclick="showDetail('${name}',${i})">${r.map((x,j)=>`<td>${j===r.length-1&&['Clientes','Obras','Presupuestos'].includes(name)?pill(String(x)):x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;$('.filter').oninput=e=>{[...document.querySelectorAll('tbody tr')].forEach(tr=>tr.style.display=tr.innerText.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')}}
function photos(){title.textContent='Fotos de obras';content.innerHTML=`<div class="toolbar"><button class="primary" onclick="demoAdd('Foto')">+ Añadir foto</button></div><div class="photos">${Array.from({length:6},(_,i)=>`<div class="photo" title="Foto de demostración ${i+1}"></div>`).join('')}</div>`}
function agenda(){title.textContent='Agenda';let ev={23:'Visita · Guardamar',24:'Enviar presupuesto',25:'Inicio · Torrevieja',28:'Llamar cliente'};content.innerHTML=`<div class="panel"><h2>Septiembre 2026</h2><div class="calendar">${['L','M','X','J','V','S','D'].map(x=>`<b>${x}</b>`).join('')}${Array.from({length:35},(_,i)=>{let d=i-1;return `<div class="day">${d>0&&d<=30?`<b>${d}</b>${ev[d]?`<div class="event">${ev[d]}</div>`:''}`:''}</div>`}).join('')}</div></div>`}
function render(v){if(v==='dashboard')dashboard();if(v==='clientes')tableView('Clientes',['Cliente','Ciudad','Teléfono','Trabajo','Estado'],clients);if(v==='obras')tableView('Obras',['Obra','Ciudad','Trabajo','Progreso','Estado'],works.map(w=>[w[0],w[1],w[2],w[3]+'%',w[4]]));if(v==='presupuestos')tableView('Presupuestos',['Nº','Cliente','Trabajo','Importe','Estado'],quotes);if(v==='documentos')tableView('Documentos',['Archivo','Cliente','Tipo','Fecha'],docs);if(v==='fotos')photos();if(v==='agenda')agenda()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view);document.querySelector('.app').classList.remove('open')});$('#menu').onclick=()=>document.querySelector('.app').classList.toggle('open');
$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){document.querySelector('[data-view="clientes"]').click();setTimeout(()=>{$('.filter').value=e.target.value;$('.filter').dispatchEvent(new Event('input'))},0)}};
function showDetail(type,i){let r= type==='Clientes'?clients[i]:type==='Obras'?works[i]:type==='Presupuestos'?quotes[i]:docs[i];$('#modalContent').innerHTML=`<h2>${type} · Detalle</h2><p class="muted">Ficha demostrativa. Todos los datos son ficticios.</p><div class="detailgrid">${r.map((x,j)=>`<div class="detail"><small>Campo ${j+1}</small><b>${x}</b></div>`).join('')}</div><br><button class="primary" onclick="closeModal()">Cerrar</button>`;$('#modal').classList.remove('hidden')}
function demoAdd(type){$('#modalContent').innerHTML=`<h2>Nuevo · ${type}</h2><p>En la versión final, desde aquí se podría crear un nuevo registro y guardarlo en la base de datos local.</p><p class="muted">Esta versión web es una demostración visual y no almacena datos reales.</p><button class="primary" onclick="closeModal()">Entendido</button>`;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}window.closeModal=closeModal;window.showDetail=showDetail;window.demoAdd=demoAdd;render('dashboard');
